### ISSUE TITLE
Athenian Spearman has no build animation

### ISSUE THREAD

**Issue by AlexanderMrgdo** [SlavomirSlovenkai/0ad-gameplay-mode#1]
![1](https://user-images.githubusercontent.com/29136612/50727590-68a12780-10f3-11e9-90aa-0571677ddbbd.PNG)

**Comment by AlexanderMrgdo** [comment]
Found the same issue with the athenian archer
![2](https://user-images.githubusercontent.com/29136612/50727711-20830480-10f5-11e9-9828-c3481dc203c4.PNG)

**Comment by LenaTheWolfess** [comment]
Thank you for interest and reporting this. :) I am sorry this bug is part of the mod and you had to experience, it is my failure. 
In the fact they have the animation, game just fails to choose it (just little excuse :) ) anyway I am preparing  battalion system with next update and army will be just for fighting so this will not be problem anymore.

**Comment by AlexanderMrgdo** [comment]
i belive it was because those actors had only build_farm variant and not build, so you can find that bug in case it appears in other actor.
